#[derive(Debug, PartialEq, Copy, Clone)]
pub enum Keyword {
    Author,
    BScale,
    BUnit,
    BZero,
    BitPix,
    Blank,
    Blocked,
    CheckSum,
    Comment,
    Continue,
    DataMax,
    DataMin,
    DataSum,
    Date,
    DateObs,
    End,
    Epoch,
    Equinox,
    ExtLevel,
    ExtName,
    ExtVer,
    Extend,
    FZALGn(u16),
    FZAlgor,
    FZTileLn,
    GCount,
    Groups,
    History,
    Inherit,
    Instrume,
    NAxis,
    NAxisn(u16),
    Object,
    Obs,
    Observer,
    Origin,
    PCount,
    PScaln(u16),
    PTypen(u16),
    PZeron(u16),
    Referenc,
    Simple,
    TBcoln(u16),
    TDMaxn(u16),
    TDMinn(u16),
    TDimn(u16),
    TDispn(u16),
    TFromn(u16),
    THeap,
    TLMaxn(u16),
    TLMinn(u16),
    TNulln(u16),
    TScaln(u16),
    TTypen(u16),
    TUnitn(u16),
    TZeron(u16),
    Telescop,
    Tfields,
    Unknown,
    Xtension,
    ZBitPix,
    ZBlocked,
    ZCTypn,
    ZCmpType,
    ZDataSum,
    ZDither0,
    ZExtend,
    ZFormn,
    ZGCount,
    ZImage,
    ZMaskCmp,
    ZNAMEi(u16),
    ZNaxis,
    ZNaxis1,
    ZNaxis2,
    ZPCount,
    ZQuantiz,
    ZSimple,
    ZTHeap,
    ZTable,
    ZTension,
    ZTileLen,
    ZTilen(u16),
    ZVALi,
    ZheckSum,
}

impl From<&[u8]> for Keyword {
    fn from(i: &[u8]) -> Self {
        match i {
            b"COMMENT " => Keyword::Comment,
            b"SIMPLE  " => Keyword::Simple,
            b"BITPIX  " => Keyword::BitPix,
            b"NAXIS   " => Keyword::NAxis,
            b"END" => Keyword::End,
            _ => Keyword::Unknown,
            b"AUTHOR  " => Keyword::Author,
            b"" => Keyword::BScale,
            " => Keyword::BUnit,
            " => Keyword::BZero,
            " => Keyword::BitPix,
            " => Keyword::Blank,
            " => Keyword::Blocked,
            " => Keyword::CheckSum,
            " => Keyword::Comment,
            " => Keyword::Continue,
            " => Keyword::DataMax,
            " => Keyword::DataMin,
            " => Keyword::DataSum,
            " => Keyword::Date,
            " => Keyword::DateObs,
            " => Keyword::End,
            " => Keyword::Epoch,
            " => Keyword::Equinox,
            " => Keyword::ExtLevel,
            " => Keyword::ExtName,
            " => Keyword::ExtVer,
            " => Keyword::Extend,
            " => Keyword::FZALGn(u16),
            " => Keyword::FZAlgor,
            " => Keyword::FZTileLn,
            " => Keyword::GCount,
            " => Keyword::Groups,
            " => Keyword::History,
            " => Keyword::Inherit,
            " => Keyword::Instrume,
            " => Keyword::NAxis,
            " => Keyword::NAxisn(u16),
            " => Keyword::Object,
            " => Keyword::Obs,
            " => Keyword::Observer,
            " => Keyword::Origin,
            " => Keyword::PCount,
            " => Keyword::PScaln(u16),
            " => Keyword::PTypen(u16),
            " => Keyword::PZeron(u16),
            " => Keyword::Referenc,
            " => Keyword::Simple,
            " => Keyword::TBcoln(u16),
            " => Keyword::TDMaxn(u16),
            " => Keyword::TDMinn(u16),
            " => Keyword::TDimn(u16),
            " => Keyword::TDispn(u16),
            " => Keyword::TFromn(u16),
            " => Keyword::THeap,
            " => Keyword::TLMaxn(u16),
            " => Keyword::TLMinn(u16),
            " => Keyword::TNulln(u16),
            " => Keyword::TScaln(u16),
            " => Keyword::TTypen(u16),
            " => Keyword::TUnitn(u16),
            " => Keyword::TZeron(u16),
            " => Keyword::Telescop,
            " => Keyword::Tfields,
            " => Keyword::Unknown,
            " => Keyword::Xtension,
            " => Keyword::ZBitPix,
            " => Keyword::ZBlocked,
            " => Keyword::ZCTypn,
            " => Keyword::ZCmpType,
            " => Keyword::ZDataSum,
            " => Keyword::ZDither0,
            " => Keyword::ZExtend,
            " => Keyword::ZFormn,
            " => Keyword::ZGCount,
            " => Keyword::ZImage,
            " => Keyword::ZMaskCmp,
            " => Keyword::ZNAMEi(u16),
            " => Keyword::ZNaxis,
            " => Keyword::ZNaxis1,
            " => Keyword::ZNaxis2,
            " => Keyword::ZPCount,
            " => Keyword::ZQuantiz,
            " => Keyword::ZSimple,
            " => Keyword::ZTHeap,
            " => Keyword::ZTable,
            " => Keyword::ZTension,
            " => Keyword::ZTileLen,
            " => Keyword::ZTilen(u16),
            " => Keyword::ZVALi,
            " => Keyword::ZheckSum,
                }
    }
}

#[derive(Debug, PartialEq)]
pub enum ValueType {
    CharacterString,
    ComplexFloat,
    ComplexInteger,
    ContinuedString,
    Date,
    Integer,
    Logical,
    Real,
    Unknown,
}
